name: flutter_opencc_ffi_platform_interface
description: A common platform interface for the flutter_opencc_ffi plugin.
repository: https://github.com/dolphinxx/flutter_opencc_ffi/tree/master/flutter_opencc_ffi_platform_interface
issue_tracker: https://github.com/dolphinxx/flutter_opencc_ffi/issues
version: 0.0.3
publish_to: none  # 패키지 배포를 막음

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter